### ISSUE TITLE
error open ihack.py file

### ISSUE THREAD

**Issue by hardasmith2** [termuxhackers-id/INSTAHACK#15]
python3 ihack.py
SyntaxError: Non-UTF-8 code starting with '\xa7'

**Comment by h4x3r1** [comment]
Using what?

**Comment by h4x3r1** [comment]
> python3 ihack.py SyntaxError: Non-UTF-8 code starting with '\xa7'

Using which os?

**Comment by h4x3r1** [comment]
> i use kali linux

Umm, This tool has coded properly ! 
`rm -rf INSTAHACK`
Install the tool again !

**Comment by hardasmith2** [comment]
![sddsdsd](https://github.com/termuxhackers-id/INSTAHACK/assets/42210107/98060c1b-68f6-4839-ad0e-d82fd1a381fc)
Already full command installation, still same problem

**Comment by termuxhackers-id** [comment]
Updated!

**Comment by Kr0966** [comment]
Can anyone help me how to use this tool ?
