### ISSUE TITLE
Problem with execute the script (wrong way to obfuscate?)

### ISSUE THREAD

**Issue by Ar1sto** [termuxhackers-id/INSTAHACK#20]
─$ python3 ihack.py                                        
SyntaxError: Non-UTF-8 code starting with '\xa7' in file /home/xxx/INSTAHACK/ihack.py on line 2, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details

i installed all requirements, so don't come with that bs

**Comment by shohag288** [comment]
Hello, This is Shohag. I am a professional Ethical Hacker,
Security Specialist as well as Penetration Tester. I can test the following vulnerability and I will provide you with a perfect assessment of your website security
which makes your website safe and sound.

My Experience:
💗. Recovering Hacked WordPress Website
💗. Full Vulnerability Scan and WordPress website malware removal
💗. Vulnerability Assessment
💗. Antispam protection
💗. Analysis of database servers
💗. Restore a hacked website
💗. Ethical Hacking(White Hat Hacker)
💗. Hacked account recovery
💗. Password recovery
💗. Decode encrypted files
💗. Vulnerability Testing
💗....my  WhatsApp number +8801314956025

**Comment by termuxhackers-id** [comment]
Only for termux
