### ISSUE TITLE
Bug report : README.md

### ISSUE THREAD

**Issue by Gsa24** [termuxhackers-id/INSTAHACK#21]
```pkg update -y && pkg upgrade -y && pkg install git nano wget python python-pip && pip install wheel rich bs4 pystyle pynacl requests licensing pycryptodomex && python3 ihack.py```

**Comment by termuxhackers-id** [comment]
Already update for installing pynacl, check readme md now

**Comment by Nedwi-ID** [comment]
> Already update for installing pynacl, check readme md now

There is no git clone 

> Already update for installing pynacl, check readme md now

There is no git clone https://github.com/termuxhackers-id/INSTAHACK in your Readme!!!
