### ISSUE TITLE
After this update i cant log ;

### ISSUE THREAD

**Issue by h4x3r1** [termuxhackers-id/INSTAHACK#5]
![Screenshot_20230418_085839_Termux](https://user-images.githubusercontent.com/92029487/232660239-b5faecf8-1b2c-45fe-bc21-7b171daacf44.jpg)

![Screenshot_20230418_090128_Termux](https://user-images.githubusercontent.com/92029487/232660262-abe9c6a4-cfca-4a28-a34d-e6d65c6a7060.jpg)

**Comment by termuxhackers-id** [comment]
Fixed, git pull

**Comment by h4x3r1** [comment]
> Fixed, git pull

Thanks 🌐
