### ISSUE TITLE
error while running ihack.py

### ISSUE THREAD

**Issue by Itsamanjain** [termuxhackers-id/INSTAHACK#50]
geting this error while running python3 ihack.py
![Screenshot from 2024-01-16 16-01-09](https://github.com/termuxhackers-id/INSTAHACK/assets/112370476/954b277c-7057-4fb4-b16c-4a97c36653a6)

**Comment by termuxhackers-id** [comment]
> geting this error while running python3 ihack.py ![Screenshot from 2024-01-16 16-01-09](https://private-user-images.githubusercontent.com/112370476/297014902-954b277c-7057-4fb4-b16c-4a97c36653a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjYxMzQsIm5iZiI6MTcwNjAyNTgzNCwicGF0aCI6Ii8xMTIzNzA0NzYvMjk3MDE0OTAyLTk1NGIyNzdjLTcwNTctNGZiNC1iMTZjLTRhOTdjMzY2NTNhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxNjAzNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2ZkY2U5NDYyMjYwMjE5OTIwZmQwNDA4YjJiODBjNWYxNTk2OWQyMTY1NGFlOTRkZTY1MzY1OGY1OGNhOTY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bw1vNsL9IXkKW2VMwnOuRJDc565FdfrBdaJyVHe1Bjs)

Run with python 3.11

**Comment by sakshamRJ13** [comment]
bro how did u use it and did u used it on termux

**Comment by sakshamRJ13** [comment]
> geting this error while running python3 ihack.py ![Screenshot from 2024-01-16 16-01-09](https://private-user-images.githubusercontent.com/112370476/297014902-954b277c-7057-4fb4-b16c-4a97c36653a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjc2MzQsIm5iZiI6MTcwNjAyNzMzNCwicGF0aCI6Ii8xMTIzNzA0NzYvMjk3MDE0OTAyLTk1NGIyNzdjLTcwNTctNGZiNC1iMTZjLTRhOTdjMzY2NTNhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxNjI4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzIyZjZkNTVjNDgwNDMzY2Q0NjdhOGUxZWExYmM0OTkxNzE4ZmY1NGU0MzBiYmNhMGM3YmUwMDdkMGYyMDc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3khUXwd9Wy_P2UUVHglh6nTcUqUkOsD9Zcc34wdPSD0)


bro how did u use it and did u used it on termux
