### ISSUE TITLE
License Key

### ISSUE THREAD

**Issue by jijuju123** [termuxhackers-id/INSTAHACK#59]
I need the license key to go further, not sure how to acquire it. I messaged on WhatsApp, please reply. Thank you

**Comment by ajfjaickald** [comment]
https://github.com/termuxhackers-id/INSTAHACK/issues/59#issue-2203964563

**Comment by Atharva1311p** [comment]
> I need the license key to go further, not sure how to acquire it. I messaged on WhatsApp, please reply. Thank you

what the licence key??
