### ISSUE TITLE
Error while running python3 instahack.py or ihack.py

### ISSUE THREAD

**Issue by aamirswati** [termuxhackers-id/INSTAHACK#6]
python3 instahack.py
File "/home/kali/instahack/instahack.py", line 3
e
 e
  f\Z
  ^
SyntaxError: invalid non-printable character U+000B

**Comment by h4x3r1** [comment]
Are you using termux?

**Comment by termuxhackers-id** [comment]
Now for Termux and Kali just run ```ihack.py```
